<x-guest-layout>
    <x-slot:title>
        {{ __('Contact page') }}
    </x-slot>
    
    <h1 class="block text-3xl font-bold mb-4">Contact</h1>
    <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae libero id sapien pellentesque malesuada. Fusce ut semper massa, non tempus metus. Donec congue ante ut ipsum blandit tincidunt. Praesent ac tortor odio. Donec pulvinar orci sed justo sodales pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin accumsan nibh ut erat luctus, et cursus tortor ornare. Nunc sodales quis nisi ut vestibulum. Etiam sit amet aliquam urna. Morbi erat dui, tincidunt ut metus non, varius malesuada leo. Cras ipsum leo, imperdiet quis enim quis, ultricies lacinia nulla.</p>
    <p class="mb-4">Mauris malesuada, ipsum vitae porttitor aliquam, lorem erat scelerisque quam, vitae rutrum turpis dui ut purus. Sed quis eleifend enim. Curabitur quis tincidunt mauris. Mauris id efficitur magna. Duis molestie fermentum lorem id commodo. In eget sagittis eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed rutrum quis orci a fringilla.</p>
    <p class="mb-4">Nam eget mi non nulla dapibus euismod vel vitae leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce porttitor porttitor ex sed bibendum. Nunc elementum, elit condimentum sagittis venenatis, erat sapien viverra ligula, et vulputate turpis nisi in urna. Maecenas et mi sodales, viverra felis pulvinar, egestas massa. Pellentesque eget dapibus lorem. Nunc eros urna, ultrices quis ex non, blandit porta velit. Duis blandit mollis nunc, vel mattis odio pharetra in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut maximus libero, eget bibendum nisl.</p>
    <p class="mb-4">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut tempus egestas nisl, ac ornare nisi maximus vel. Morbi at dignissim sem. Sed sed erat mollis, consequat orci a, cursus urna. Nullam aliquam vestibulum tellus elementum aliquam. Vestibulum porttitor orci sit amet turpis porta, vel feugiat lacus sollicitudin. Pellentesque quis enim hendrerit, molestie nibh sit amet, consectetur orci. Cras feugiat mollis lacinia. Mauris eleifend neque eu ultricies egestas. Proin maximus magna ut mi dignissim, in interdum tortor dictum. Fusce sollicitudin sem quis pretium aliquam. Nullam facilisis finibus nulla at iaculis. Aenean vel consequat ante, at euismod nunc.</p>

</x-guest-layout>